language: node_js
node_js:
- node
services:
- mysql
addons:
  ssh_known_hosts: do2.symphonious.net
before_install:
- mysql -e 'CREATE DATABASE moolah;'
before_deploy:
- openssl aes-256-cbc -K $encrypted_c03abb7c1561_key -iv $encrypted_c03abb7c1561_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  slack:
    secure: zoA2QtW6rm1TPhuPyWWgK5fYFhpYF5CNCcilCYwwTpoNB6W8B1xWKzjl1PIy/ZNzMTGUUUPfe/sXJC2BtI96ojEDSZ/Cjei6pkv5LbwQ8GLdp8vapuHJ2Jo0UGQMjNnjXhwbvPnG9NgJfcxEJoM611AFgkXmTGorwL6r/amIHShS1P4sOe3s1vgsaHxIbF+XJ9agGTiV8LYhacYKMIG1g81XSGki1+cUeHo1iyAxfvlFH4Pwur3xllHR74XC4W5cequSAIv0M6sENkqYI8Gje+UGaA8sS48Kwmgs1QR0C0fEng7efUpm4MjDzYBeeiI0hTgnYtSc+2xAjxvhpuIk5Br+Diy7Fxnsv25LYvQDdEfJ+bRddLh0vWoCzRqNMn0vaauoOyxikQE0blXkYOlIq0uTU9J5QKcz25q9pxZjCbdbmC9uavREi2IuIiEXmP83SWyI7tjd3IlFdzAbitlZzEmRMkdndB1M0XSRonAt/NzJFNd7X0wQB0REWOy9NlKLA51syCQyT4M1TGmzFQtvhZQ3IadOQc+i07FYRFV4blP2HuGazAoD/mmoIuYVLzIYtMQ1cUtvCAOOInkiULI1XKsLW9GLlTb4APghKl63jaz6dBhVGiBhdDm+lkd3qzRrpz8M5c57A//pjkC95sXUefjo9n6CTW1RIGyuBeAEAHE=
